# Generated by Django 3.2.16 on 2023-01-31 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220905_0308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_management', '0002_orderdelivery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdelivery',
            unique_together={('delivery_agent', 'order')},
        ),
    ]
