# Generated by Django 3.2.16 on 2023-05-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0003_alter_orderdelivery_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='order_active',
            field=models.BooleanField(default=False),
        ),
    ]
