# Generated by Django 3.2.11 on 2022-04-30 11:46

import apis.promotions.utils.media_paths
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apis.promotions.utils.media_paths.promotion_image_path)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('station', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_promotions', to='stations.station')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
