from apis.notifications.consumers.rider_consumers import RiderNotificationConsumer
from apis.notifications.consumers.customer_consumers import CustomerNotificationConsumer



rider_notification_consumer_websocket = RiderNotificationConsumer.as_asgi()
customer_notification_consumer_websocket = CustomerNotificationConsumer.as_asgi()

