# Generated by Django 3.2.11 on 2022-06-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
