# Generated by Django 3.2.11 on 2022-06-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bar_code',
        ),
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
