# Generated by Django 3.2.11 on 2022-01-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
