# Generated by Django 3.2.11 on 2022-04-30 11:46

import apis.orders.utils.order_generation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_key', models.CharField(blank=True, default=apis.orders.utils.order_generation.create_order_key, max_length=40, null=True, unique=True)),
                ('order_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('dispatched', 'Dispatched')], max_length=250, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=250, null=True)),
                ('base_price', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('service_charges', models.FloatField(blank=True, null=True)),
                ('delivery_charges', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('NGN', 'NGN'), ('percentage', 'PERCENTAGE')], max_length=30, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('returned_amount', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash_on_delivery', 'Cash on Delivery'), ('card', 'Card'), ('cash_in_hand', 'Cash in Hand')], max_length=250, null=True)),
                ('pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_orders', to='stations.station')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_item', to='inventory.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
