# Generated by Django 4.0.5 on 2022-08-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='returned_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Delivered'), (3, 'Cancelled'), (4, 'Returned'), (5, 'Dispatched')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(blank=True, choices=[(1, 'Pay Online'), (2, 'Wallet')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed')], default=1, null=True),
        ),
    ]
