# Generated by Django 4.0.5 on 2022-08-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_returned_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Delivered'), (4, 'Cancelled'), (5, 'Returned'), (6, 'Dispatched')], default=1, null=True),
        ),
    ]
