# Generated by Django 4.0.5 on 2022-08-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Cancelled'), (4, 'Returned'), (5, 'Dispatched'), (6, 'Completed')], default=1, null=True),
        ),
    ]
