# Generated by Django 4.0.5 on 2022-08-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_time_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_key',
            new_name='order_number',
        ),
    ]
