# Generated by Django 4.0.5 on 2022-08-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('orders', '0007_rename_order_key_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='transactions.transaction'),
        ),
    ]
