# Generated by Django 3.2.11 on 2022-09-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_datetime',
        ),
    ]
