# Generated by Django 3.2.11 on 2022-01-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
