# Generated by Django 3.2.11 on 2022-02-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'deliveries'},
        ),
    ]
