# Generated by Django 4.0.5 on 2022-08-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='building',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='apartment_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='house_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
