# Generated by Django 4.0.5 on 2022-08-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customeraddress_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_support',
            field=models.BooleanField(default=False),
        ),
    ]
