# Generated by Django 3.2.16 on 2023-03-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230323_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='fcm_token',
            field=models.CharField(blank=True, default=None, help_text='This token is used to send firebase notifications to a particular device.', max_length=200, null=True),
        ),
    ]
