# Generated by Django 3.2.11 on 2022-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccountPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flw_ref', models.CharField(max_length=30)),
                ('device_fingerprint', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('charged_amount', models.FloatField()),
                ('app_fee', models.FloatField()),
                ('merchant_fee', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('customer_fullname', models.CharField(max_length=30)),
                ('customer_phone_number', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
